MYSQL_DATABASE
railway


MYSQL_PUBLIC_URL
mysql://root:kjBYXTqAhnPppMPoBoLgWvPVQbANjFAD@shortline.proxy.rlwy.net:54625/railway




MYSQL_ROOT_PASSWORD
kjBYXTqAhnPppMPoBoLgWvPVQbANjFAD



MYSQL_URL
mysql://root:kjBYXTqAhnPppMPoBoLgWvPVQbANjFAD@mysql.railway.internal:3306/railway



MYSQLDATABASE
railway



MYSQLHOST
mysql.railway.internal



MYSQLPASSWORD
kjBYXTqAhnPppMPoBoLgWvPVQbANjFAD



MYSQLPORT
3306



MYSQLUSER
root




